import { useState } from 'react';
import { Link } from 'react-router-dom';

const units = [
  { name: 'Hospital Central', type: 'Hospital', address: 'Av. Central, 1200 - Centro', rooms: [{ name: 'Consultório 03', type: 'Consultório médico', owner: 'Dr. Carlos Silva', state: 'Em atendimento' }, { name: 'Consultório 05', type: 'Consultório médico', owner: 'Dra. Fernanda Alves', state: 'Livre' }, { name: 'Sala Vermelha', type: 'Emergência', owner: 'Equipe de emergência', state: 'Monitorada' }, { name: 'Farmácia Central', type: 'Farmácia', owner: 'Farmácia da unidade', state: 'Operacional' }] },
  { name: 'UPA Norte', type: 'UPA', address: 'Rua Norte, 450 - Jardim Norte', rooms: [{ name: 'Sala Vermelha', type: 'Emergência', owner: 'Equipe de emergência', state: 'Monitorada' }, { name: 'Consultório 01', type: 'Consultório médico', owner: 'Dr. Ricardo Nunes', state: 'Livre' }, { name: 'Sala de Exames', type: 'Exames e diagnóstico', owner: 'Equipe de exames', state: 'Operacional' }, { name: 'Farmácia UPA Norte', type: 'Farmácia', owner: 'Farmácia da unidade', state: 'Operacional' }] },
];

export default function RoomsPage() {
  const [selectedUnit, setSelectedUnit] = useState(0);
  const unit = units[selectedUnit];
  return <div className="page-wrap rooms-page"><header className="page-header"><div><p className="eyebrow">Configuração operacional</p><h2>Unidades e salas</h2><p className="page-subtitle">Organize endereços, salas, profissionais responsáveis e setores de cada unidade.</p></div><button type="button" className="primary-button"><i className="fas fa-plus" /> Nova sala</button></header><div className="rooms-layout"><aside className="unit-selector reference-card"><div className="card-heading"><i className="fas fa-building" /> Unidades</div>{units.map((item, index) => <button type="button" className={index === selectedUnit ? 'unit-selector-item selected' : 'unit-selector-item'} onClick={() => setSelectedUnit(index)} key={item.name}><span className="unit-selector-icon"><i className={item.type === 'UPA' ? 'fas fa-truck-medical' : 'fas fa-hospital'} /></span><span><strong>{item.name}</strong><small>{item.type} · {item.rooms.length} salas</small></span><i className="fas fa-chevron-right" /></button>)}</aside><main><section className="unit-hero reference-card"><div className="unit-hero-icon"><i className="fas fa-hospital" /></div><div><p className="eyebrow">Unidade selecionada</p><h3>{unit.name}</h3><span><i className="fas fa-location-dot" /> {unit.address}</span></div><span className="status-pill status-active">Operacional</span></section><div className="rooms-toolbar"><div><h3>Salas e setores</h3><p>Defina quem atende em cada espaço e qual fluxo ele executa.</p></div><select><option>Todas as categorias</option><option>Consultórios</option><option>Exames</option><option>Farmácia</option><option>Emergência</option></select></div><div className="room-grid">{unit.rooms.map((room) => <article className={room.name === 'Sala Vermelha' ? 'room-card red-room-card' : 'room-card'} key={room.name}><div className="room-card-top"><span className="room-type-icon"><i className={room.name === 'Sala Vermelha' ? 'fas fa-truck-medical' : room.type === 'Farmácia' ? 'fas fa-pills' : room.type === 'Exames e diagnóstico' ? 'fas fa-microscope' : 'fas fa-stethoscope'} /></span><span className="status-pill status-active">{room.state}</span></div><h3>{room.name}</h3><p>{room.type}</p><div className="room-owner"><i className="fas fa-user-doctor" /><span><small>Responsável</small><strong>{room.owner}</strong></span></div><footer><button type="button">Editar sala</button>{room.name === 'Sala Vermelha' ? <Link to="/sala-vermelha">Abrir módulo <i className="fas fa-arrow-right" /></Link> : <button type="button">Ver fila</button>}</footer></article>)}</div></main></div></div>;
}
